### ISSUE TITLE
RFC: parse git commit log for fragments

### ISSUE THREAD

**Issue by refack** [hawkowl/towncrier#135]
Seeking comments on a complimentary approach for extracting fragments - parse the git log for marked up parts. Similar to the approach used in nodejs/node (e.g. https://github.com/nodejs/node/commit/c3dd0d001abdb983d19987c76cad7ef30ef82a25).
As I imagine this:
1. Author adds some marked up metadata to the commit message (`.feature: add foo to bar`)
2. During release creating `towncrier` either infers the commit range, or is given manually
3. `towncrier` parses message in commit range for fragments
4. git fragments and file fragments lists are merged
5. profit

**Comment by hawkowl** [comment]
Towncrier explicitly doesn't do this for several reasons:

- Git history is malleable and not trustworthy (e.g. if someone squash merges something by accident)
- Merge commits are done at merge time, and not always by the person working on the actual task. This means that one has to do extra work to have the news text actually be part of the review, vs just part of the diff.
- Things that check the newsfile then need a significant amount of history and can't be shallow clones.
- uuuuuuuuuuuuuugh interfacing with git

But, yeah, it's designed to make it as separate as possible, as the person doing the git may not be the one writing the newsfile, It also means that you'd need to figure out which commit messages override which, which depends on your local tree if one cherry-picks a fix with a newsfile commit and then merges that in later. Also, editing newsfiles either means editing commits and force-pushing, or relying on the above "which one has precedence" figuring out in the git graph.

**Comment by xixixao** [comment]
> Git history is malleable and not trustworthy (e.g. if someone squash merges something by accident)

This is in general not an issue for `main` in team projects. Squashing is fine, the squashed commit can be used.

> Merge commits are done at merge time, and not always by the person working on the actual task.

That's not usually the case, it's usually the PR/MR author who "writes" the merge commit. Ideally the merge commit is just the PR/MR title+body. Editing by others could be a strength though.

> This means that one has to do extra work to have the news text actually be part of the review, vs just part of the diff.

If the PR/MR body is taken, then the reviewer needs to review the PR/MR description. This should be the case anyway. This applies when squashing. When not squashing, individual commit messages can be reviewed for fragments (but this is likely not the ideal/usual workflow).

> Things that check the newsfile then need a significant amount of history and can't be shallow clones.

Not sure what those "things" are.

> uuuuuuuuuuuuuugh interfacing with git

Pretty simple.

> But, yeah, it's designed to make it as separate as possible, as the person doing the git may not be the one writing the newsfile,

If this is the case, then I would probably avoid the complexity of towncrier / commitizen and go back to having a single person write the CHANGELOG manually.

> overriding

No overriding. In our case we will publish to Gitlab Releases, where the changelog can be edited afterwards.

I think there are clear benefits to using commit messages:

1. Not requiring file changes when tinkering with changelog in MR/PR review
2. No need to figure out the file name (issues are often internal, so using them for this use case goes against the spirit of keeping the changelog public facing)
3. Releasing doesn't require another commit (although towncrier at least makes them non-conflicting)

Using git overall feels more lightweight for developers, which in our case is important, since we might have many people who want to publish changes (from a monorepo, so conventional commits approaches don't work for us).

**Comment by adiroiban** [comment]
Thanks Michal, for the feedback.

I am happy to consider alternative release notes fragments sources

Maybe we can build something on top of these commit conventions .
https://www.conventionalcommits.org/en/v1.0.0/

and I think there are already tools to extract release notes that are generated using this standard

https://github.com/conventional-changelog/conventional-changelog

https://github.com/release-it/release-it

---------

The advantage of a release notes fragment file, is that you can review and provide feedback during the normal PR process.

------

So... maybe there are already other tools that are extracting release notes from git commits ... so we don't need to reinvent the wheel in `towncrier`


-------

So, before starting any extra work, it will help to do a "state of the art" study to make sure we add new value in `towncrier` and not only just reinventing the wheel
